/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        studio: {
          darkest: 'var(--ui-surface-base)',
          darker: 'var(--ui-surface-low)',
          dark: 'var(--ui-surface-raised)',
          panel: 'var(--ui-surface-overlay)',
          border: 'var(--ui-border-default)',
          hover: 'var(--ui-surface-highest)',
          accent: 'var(--ui-primary-container)',
          accentHover: 'var(--ui-primary-hover)',
          amber: 'var(--ui-warning)',
          emerald: 'var(--ui-success)',
          rose: 'var(--ui-danger)',
        },
        surface: {
          DEFAULT: 'var(--ui-surface-base)',
          base: 'var(--ui-surface-base)',
          dim: 'var(--ui-surface-base)',
          bright: 'var(--ui-surface-highest)',
          container: 'var(--ui-surface-raised)',
          'container-lowest': 'var(--ui-surface-canvas)',
          'container-low': 'var(--ui-surface-low)',
          'container-high': 'var(--ui-surface-overlay)',
          'container-highest': 'var(--ui-surface-highest)',
        },
        'on-surface': 'var(--ui-text-primary)',
        'on-surface-variant': 'var(--ui-text-secondary)',
        outline: 'var(--ui-outline)',
        'outline-variant': 'var(--ui-border-default)',
        primary: {
          DEFAULT: 'var(--ui-primary)',
          container: 'var(--ui-primary-container)',
          fixed: 'var(--ui-primary-fixed)',
        },
        'on-primary': 'var(--ui-on-primary)',
        'on-primary-container': 'var(--ui-on-primary-container)',
        secondary: {
          DEFAULT: 'var(--ui-warning)',
          container: 'var(--ui-warning-container)',
        },
        'on-secondary': 'var(--ui-on-warning-container)',
        tertiary: {
          DEFAULT: 'var(--ui-success)',
          container: 'var(--ui-success-container)',
          fixed: 'var(--ui-success-fixed)',
        },
        'on-tertiary': 'var(--ui-on-tertiary)',
      },
      fontFamily: {
        mono: ['var(--ui-font-mono)'],
        sans: ['var(--ui-font-family)'],
        'code-coordinate': ['JetBrains Mono', 'monospace'],
        'code-matrix': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['var(--ui-font-label)', { lineHeight: 'var(--ui-line-control)', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['var(--ui-font-control)', { lineHeight: 'var(--ui-line-control)', letterSpacing: '0.02em', fontWeight: 'var(--ui-weight-control)' }],
        'code-coordinate': ['11px', { lineHeight: '14px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'code-matrix': ['10px', { lineHeight: '12px', letterSpacing: '-0.03em', fontWeight: '400' }],
      },
      boxShadow: { DEFAULT: "var(--ui-shadow-chrome)", lg: "var(--ui-shadow-overlay)", xl: "var(--ui-shadow-overlay)", "2xl": "var(--ui-shadow-overlay)" },
      transitionDuration: { DEFAULT: "var(--ui-transition-duration)" },
      transitionTimingFunction: { DEFAULT: "var(--ui-transition-easing)" },
      borderRadius: {
        none: 'var(--ui-radius-control)',
        DEFAULT: 'var(--ui-radius-control)',
        sm: 'var(--ui-radius-control)',
        md: 'var(--ui-radius-control)',
        lg: 'var(--ui-radius-control)',
        xl: 'var(--ui-radius-control)',
        '2xl': 'var(--ui-radius-control)',
        '3xl': 'var(--ui-radius-control)',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
